// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/darrior/urlshortener/internal/service (interfaces: IService)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mock_service.go -package=mocks github.com/darrior/urlshortener/internal/service IService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/darrior/urlshortener/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockIService is a mock of IService interface.
type MockIService struct {
	ctrl     *gomock.Controller
	recorder *MockIServiceMockRecorder
	isgomock struct{}
}

// MockIServiceMockRecorder is the mock recorder for MockIService.
type MockIServiceMockRecorder struct {
	mock *MockIService
}

// NewMockIService creates a new mock instance.
func NewMockIService(ctrl *gomock.Controller) *MockIService {
	mock := &MockIService{ctrl: ctrl}
	mock.recorder = &MockIServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIService) EXPECT() *MockIServiceMockRecorder {
	return m.recorder
}

// AddURL mocks base method.
func (m *MockIService) AddURL(ctx context.Context, userID, longURL string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddURL", ctx, userID, longURL)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddURL indicates an expected call of AddURL.
func (mr *MockIServiceMockRecorder) AddURL(ctx, userID, longURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddURL", reflect.TypeOf((*MockIService)(nil).AddURL), ctx, userID, longURL)
}

// AddURLs mocks base method.
func (m *MockIService) AddURLs(ctx context.Context, userID string, longURLs models.ShortenerBatchRequest) (models.ShortenerBatchResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddURLs", ctx, userID, longURLs)
	ret0, _ := ret[0].(models.ShortenerBatchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddURLs indicates an expected call of AddURLs.
func (mr *MockIServiceMockRecorder) AddURLs(ctx, userID, longURLs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddURLs", reflect.TypeOf((*MockIService)(nil).AddURLs), ctx, userID, longURLs)
}

// GetURL mocks base method.
func (m *MockIService) GetURL(ctx context.Context, id string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetURL", ctx, id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetURL indicates an expected call of GetURL.
func (mr *MockIServiceMockRecorder) GetURL(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetURL", reflect.TypeOf((*MockIService)(nil).GetURL), ctx, id)
}

// Ping mocks base method.
func (m *MockIService) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockIServiceMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockIService)(nil).Ping), ctx)
}
