// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/darrior/urlshortener/internal/service (interfaces: IService)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mock_service.go -package=mocks github.com/darrior/urlshortener/internal/service IService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	api "github.com/darrior/urlshortener/internal/models/api"
	models "github.com/darrior/urlshortener/internal/service/models"
	gomock "go.uber.org/mock/gomock"
)

// MockIService is a mock of IService interface.
type MockIService struct {
	ctrl     *gomock.Controller
	recorder *MockIServiceMockRecorder
	isgomock struct{}
}

// MockIServiceMockRecorder is the mock recorder for MockIService.
type MockIServiceMockRecorder struct {
	mock *MockIService
}

// NewMockIService creates a new mock instance.
func NewMockIService(ctrl *gomock.Controller) *MockIService {
	mock := &MockIService{ctrl: ctrl}
	mock.recorder = &MockIServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIService) EXPECT() *MockIServiceMockRecorder {
	return m.recorder
}

// AddURL mocks base method.
func (m *MockIService) AddURL(ctx context.Context, userID, longURL string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddURL", ctx, userID, longURL)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddURL indicates an expected call of AddURL.
func (mr *MockIServiceMockRecorder) AddURL(ctx, userID, longURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddURL", reflect.TypeOf((*MockIService)(nil).AddURL), ctx, userID, longURL)
}

// AddURLs mocks base method.
func (m *MockIService) AddURLs(ctx context.Context, userID string, longURLs api.ShortenerBatchRequest) (api.ShortenerBatchResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddURLs", ctx, userID, longURLs)
	ret0, _ := ret[0].(api.ShortenerBatchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddURLs indicates an expected call of AddURLs.
func (mr *MockIServiceMockRecorder) AddURLs(ctx, userID, longURLs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddURLs", reflect.TypeOf((*MockIService)(nil).AddURLs), ctx, userID, longURLs)
}

// GetURL mocks base method.
func (m *MockIService) GetURL(ctx context.Context, id string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetURL", ctx, id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetURL indicates an expected call of GetURL.
func (mr *MockIServiceMockRecorder) GetURL(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetURL", reflect.TypeOf((*MockIService)(nil).GetURL), ctx, id)
}

// GetUserURLs mocks base method.
func (m *MockIService) GetUserURLs(ctx context.Context, userID string) (api.UserURLsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserURLs", ctx, userID)
	ret0, _ := ret[0].(api.UserURLsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserURLs indicates an expected call of GetUserURLs.
func (mr *MockIServiceMockRecorder) GetUserURLs(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserURLs", reflect.TypeOf((*MockIService)(nil).GetUserURLs), ctx, userID)
}

// NewUserID mocks base method.
func (m *MockIService) NewUserID() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewUserID")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewUserID indicates an expected call of NewUserID.
func (mr *MockIServiceMockRecorder) NewUserID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewUserID", reflect.TypeOf((*MockIService)(nil).NewUserID))
}

// Ping mocks base method.
func (m *MockIService) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockIServiceMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockIService)(nil).Ping), ctx)
}

// RemoveURLs mocks base method.
func (m *MockIService) RemoveURLs(ctx context.Context, userID string, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveURLs", ctx, userID, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveURLs indicates an expected call of RemoveURLs.
func (mr *MockIServiceMockRecorder) RemoveURLs(ctx, userID, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveURLs", reflect.TypeOf((*MockIService)(nil).RemoveURLs), ctx, userID, ids)
}

// SignClaims mocks base method.
func (m *MockIService) SignClaims(claims *models.Claims) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignClaims", claims)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SignClaims indicates an expected call of SignClaims.
func (mr *MockIServiceMockRecorder) SignClaims(claims any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignClaims", reflect.TypeOf((*MockIService)(nil).SignClaims), claims)
}

// ValidateToken mocks base method.
func (m *MockIService) ValidateToken(tokenString string) (*models.Claims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateToken", tokenString)
	ret0, _ := ret[0].(*models.Claims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateToken indicates an expected call of ValidateToken.
func (mr *MockIServiceMockRecorder) ValidateToken(tokenString any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateToken", reflect.TypeOf((*MockIService)(nil).ValidateToken), tokenString)
}
